CREATE TABLE `REQUEST_STAT` (
  `STATION_CODE` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '지하철 역 코드',
  `REQUEST_DATE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '요청 날짜',
  `REQUEST_HOUR` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '요청 시간',
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
  `UPDATED_AT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '최근 수정 일자',
  PRIMARY KEY (`STATION_CODE`,`REQUEST_HOUR`),
  CONSTRAINT `REQUEST_STAT_ibfk_1` FOREIGN KEY (`STATION_CODE`) REFERENCES `STATION` (`STATION_CODE`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;