CREATE TABLE `STAT` (
  `STATION_CODE` varchar(6) NOT NULL COMMENT '역 코드',
  `DAY` varchar(3) NOT NULL COMMENT '요일',
  `HOUR` varchar(2) NOT NULL COMMENT '시간',
  `CONGESTION_MIN_00` int NOT NULL COMMENT '00분의 혼잡도',
  `CONGESTION_MIN_10` int NOT NULL COMMENT '10분의 혼잡도',
  `CONGESTION_MIN_20` int NOT NULL COMMENT '20분의 혼잡도',
  `CONGESTION_MIN_30` int NOT NULL COMMENT '30분의 혼잡도',
  `CONGESTION_MIN_40` int NOT NULL COMMENT '40분의 혼잡도',
  `CONGESTION_MIN_50` int NOT NULL COMMENT '50분의 혼잡도',
  `START_DATE` varchar(8) NOT NULL COMMENT '통계 집계 시작일',
  `END_DATE` varchar(8) NOT NULL COMMENT '통계 집계 종료일',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최근 수정 날짜',
  PRIMARY KEY (`STATION_CODE`,`DAY`,`HOUR`,`START_DATE`),
  CONSTRAINT `STAT_ibfk_1` FOREIGN KEY (`STATION_CODE`) REFERENCES `STATION` (`STATION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;