CREATE TABLE `STATION_EXIT_USER_COUNT` (
  `STATION_CODE` varchar(6) NOT NULL COMMENT '역 코드',
  `DATE` varchar(8) NOT NULL COMMENT '요일',
  `USER_COUNT_17` int NOT NULL COMMENT '17시 치하철 사용자 수',
  `USER_COUNT_18` int NOT NULL COMMENT '18시 치하철 사용자 수',
  `USER_COUNT_19` int NOT NULL COMMENT '19시 치하철 사용자 수',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최근 수정 날짜',
  PRIMARY KEY (`STATION_CODE`,`DATE`),
  CONSTRAINT `STATION_EXIT_USER_COUNT_ibfk_1` FOREIGN KEY (`STATION_CODE`) REFERENCES `STATION` (`STATION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;