CREATE TABLE `STATION_BUNDANG_LINE` (
  `STATION_CODE` varchar(6) NOT NULL COMMENT '역 코드',
  `DISTANCE` int NOT NULL COMMENT '거리(미터)',
  `STATION_NAME` varchar(10) NOT NULL COMMENT '역 이름',
  `IS_DIRECT_STOP` int NOT NULL COMMENT '급행 정차 유무',
  `RELATIVE_STATION` varchar(6) DEFAULT NULL COMMENT '관련 역',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최근 수정 날짜',
  PRIMARY KEY (`STATION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;