CREATE TABLE `STATION_ARRIVAL_REALTIME_POSITION` (
  `TRAIN_NO` varchar(5) NOT NULL COMMENT '열차 번호',
  `TRAIN_NAME` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '열차 이름',
  `ARRIVAL_STATION_CODE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '현재 도착 역 코드',
  `ARRIVAL_MESSAGE` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '-' COMMENT '도착 정보 메세지',
  `ARRIVAL_CODE` int NOT NULL COMMENT '0:진입, 1:도착, 2:출발, 3:전역출발, 4:전역진입, 5:전역도착, 99:운행중',
  `DIRECT_AT` int NOT NULL COMMENT '0: 일반, 1: 급행',
  `UP_DN_LINE` int NOT NULL COMMENT '0 : 상행/내선, 1 : 하행/외선',
  `ARRIVAL_DATE` varchar(8) NOT NULL COMMENT '도착 날짜',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최근 수정 날짜',
  PRIMARY KEY (`TRAIN_NO`,`ARRIVAL_STATION_CODE`,`ARRIVAL_CODE`,`ARRIVAL_DATE`),
  KEY `idx_insert_date` (`ARRIVAL_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;